apiVersion: v1
kind: ConfigMap
metadata:
  name: ats-config
data:
  NODE_ENV: "production"
  PORT: "4005"
  MONGODB_URI: "mongodb://mongodb:27017/ats"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  RESUME_PARSER_URL: "http://resume-parser:8080"
  MAX_FILE_SIZE: "10485760"  # 10MB
  ALLOWED_FILE_TYPES: "pdf,doc,docx"
  DEFAULT_PAGE_SIZE: "10"