apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  CORS_ORIGIN: "*"
  RATE_LIMIT_WINDOW_MS: "900000"  # 15 minutes
  RATE_LIMIT_MAX: "100"
  BODY_PARSER_LIMIT: "10mb"
  COMPRESSION_LEVEL: "6"
  ENABLE_LOGGING: "true"