apiVersion: v1
kind: ConfigMap
metadata:
  name: meeting-config
data:
  NODE_ENV: "production"
  PORT: "4003"
  MONGODB_URI: "mongodb://mongodb:27017/meetings"
  TIMEZONE: "UTC"
  MEETING_DURATION_DEFAULT: "3600000"  # 1 hour in ms
  MAX_PARTICIPANTS: "50"
  ENABLE_RECORDING: "false"