apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  NODE_ENV: "production"
  PORT: "4001"
  MONGODB_URI: "mongodb://mongodb:27017/auth"
  JWT_SECRET: "your-jwt-secret"
  JWT_EXPIRES_IN: "1d"
  CORS_ORIGIN: "*"
  LOG_LEVEL: "info"