apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret"
  SESSION_SECRET: "your-session-secret"
  API_KEYS: '{"mobile-app": "mobile-app-secret-key", "web-app": "web-app-secret-key"}'