apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
stringData:
  username: "admin"
  password: "your-mongodb-password"
  root-password: "your-root-password"
  database: "taskpulse"
  replica-set: "rs0"