apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb://username:password@mongodb:27017/users"
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  AWS_REGION: "us-east-1"
  AWS_BUCKET_NAME: "user-avatars"