apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview-service
  template:
    metadata:
      labels:
        app: interview-service
    spec:
      containers:
      - name: interview-service
        image: taskpulse/interview-service:latest
        ports:
        - containerPort: 4004
        envFrom:
        - configMapRef:
            name: interview-config
        - secretRef:
            name: interview-secrets
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"