apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting-service
  template:
    metadata:
      labels:
        app: meeting-service
    spec:
      containers:
      - name: meeting-service
        image: taskpulse/meeting-service:latest
        ports:
        - containerPort: 4003
        envFrom:
        - configMapRef:
            name: meeting-config
        - secretRef:
            name: meeting-secrets