# infra/k8s/services/gateway.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    tier: frontend
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30001