# infra/k8s/services/interview-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: interview-service
  labels:
    app: interview-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: interview-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4004