apiVersion: v1
kind: Service
metadata:
  name: meeting-service
  labels:
    app: meeting-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: meeting-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4003