# infra/k8s/services/mongodb.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: database
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for direct pod access
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017